BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Add BTC address columns to wallets
--
--    main_btc_address    – derived from the user's mnemonic in the extension.
--                          Provided by the client on first use; used as the
--                          return address when redeeming a UTXO slot.
--
--    utxo_funding_address – generated by the rgb-lightning-node at wallet
--                          creation. BTC sent here flows into the node's shared
--                          wallet pool so /createutxos can draw from it.
--                          One permanent address per wallet — never changes.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE wallets
  ADD COLUMN IF NOT EXISTS main_btc_address      TEXT,
  ADD COLUMN IF NOT EXISTS utxo_funding_address  TEXT;

COMMENT ON COLUMN wallets.main_btc_address IS
  'User-controlled Bitcoin address derived from their mnemonic (extension-side).
   Used as the return address when redeeming a FREE or EMPTY UTXO slot.
   Supplied by the Chrome extension on first wallet interaction.';

COMMENT ON COLUMN wallets.utxo_funding_address IS
  'Node-generated Bitcoin address allocated at wallet creation time.
   The user sends exactly 0.00033 BTC here to fund one UTXO slot creation.
   Belongs to the rgb-lightning-node shared wallet pool.
   One permanent address per wallet — never regenerated.';

CREATE UNIQUE INDEX IF NOT EXISTS wallets_utxo_funding_address_idx
  ON wallets (utxo_funding_address)
  WHERE utxo_funding_address IS NOT NULL;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. utxo_deposit_requests
--
--    Tracks every "Create UTXO" action initiated by a user.
--    Flow:
--      pending    – user clicked Create UTXO, backend recorded the intent
--      confirming – tx detected on-chain, waiting for N confirmations
--      confirmed  – N confirmations reached → /createutxos called → slot born
--      expired    – no tx seen before expires_at → user must retry
--      failed     – wrong amount sent, or /createutxos call failed
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS utxo_deposit_requests (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  wallet_id             UUID        NOT NULL REFERENCES wallets(id) ON DELETE CASCADE,

  -- The node-generated address the user must send BTC to (copy of wallets.utxo_funding_address)
  deposit_address       TEXT        NOT NULL,

  -- How much the user is expected to send (default 33 000 sats = 0.00033 BTC)
  expected_sats         BIGINT      NOT NULL DEFAULT 33000,

  -- Actual amount received once the tx is detected
  received_sats         BIGINT,

  -- Confirmations required before calling /createutxos (1 for regtest, 3 for mainnet)
  required_confirmations INTEGER    NOT NULL DEFAULT 1,

  -- Current confirmation count (updated by the watcher)
  confirmations         INTEGER     NOT NULL DEFAULT 0,

  -- Bitcoin txid of the user's deposit transaction (set by watcher)
  deposit_txid          TEXT,

  -- Status of this deposit request
  status                TEXT        NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending','confirming','confirmed','expired','failed')),

  -- Which node to call /createutxos on once confirmed
  node_account_ref      TEXT        NOT NULL,

  -- FK to the slot that was born from this deposit (set after /createutxos succeeds)
  utxo_slot_id          UUID        REFERENCES user_utxo_slots(id) ON DELETE SET NULL,

  -- Error detail if status = failed
  error_message         TEXT,

  -- Deposit expires if no tx is seen within this window
  expires_at            TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),

  -- Timestamps
  detected_at           TIMESTAMPTZ,
  confirmed_at          TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE utxo_deposit_requests IS
  'One row per "Create UTXO" action. Tracks the user deposit (0.00033 BTC) from
   intent through on-chain confirmation to /createutxos call and slot creation.
   pending    – intent recorded, waiting for user to send BTC.
   confirming – tx seen on-chain, accumulating confirmations.
   confirmed  – confirmed; /createutxos called; utxo_slot_id set.
   expired    – no tx within 24 h; user must click Create UTXO again.
   failed     – wrong amount or /createutxos error; see error_message.';

COMMENT ON COLUMN utxo_deposit_requests.expected_sats      IS '33 000 sats = 0.00033 BTC. Covers one /createutxos slot (32 500 sats) + miner fee (~500 sats).';
COMMENT ON COLUMN utxo_deposit_requests.deposit_txid        IS 'Bitcoin txid of the user send from their main address to deposit_address.';
COMMENT ON COLUMN utxo_deposit_requests.node_account_ref    IS 'rgb_account_ref of the node that will call /createutxos after confirmation.';
COMMENT ON COLUMN utxo_deposit_requests.utxo_slot_id        IS 'FK to user_utxo_slots row created after /createutxos succeeds.';

-- Fast lookups
CREATE INDEX IF NOT EXISTS utxo_deposit_requests_wallet_idx
  ON utxo_deposit_requests (wallet_id, created_at DESC);

CREATE INDEX IF NOT EXISTS utxo_deposit_requests_status_idx
  ON utxo_deposit_requests (status, expires_at)
  WHERE status IN ('pending', 'confirming');

CREATE INDEX IF NOT EXISTS utxo_deposit_requests_address_idx
  ON utxo_deposit_requests (deposit_address)
  WHERE status IN ('pending', 'confirming');

-- The watcher uses this to find all active deposit addresses to monitor
CREATE INDEX IF NOT EXISTS utxo_deposit_requests_txid_idx
  ON utxo_deposit_requests (deposit_txid)
  WHERE deposit_txid IS NOT NULL;

-- Reuse the existing set_updated_at() trigger function from migration 001
DROP TRIGGER IF EXISTS utxo_deposit_requests_set_updated_at ON utxo_deposit_requests;
CREATE TRIGGER utxo_deposit_requests_set_updated_at
  BEFORE UPDATE ON utxo_deposit_requests
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;
